// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/henprasetya/omdbapi/pkg/repo/omdb (interfaces: MovieRepo)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/henprasetya/omdbapi/pkg/model"
	reflect "reflect"
)

// MockMovieRepo is a mock of MovieRepo interface
type MockMovieRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMovieRepoMockRecorder
}

// MockMovieRepoMockRecorder is the mock recorder for MockMovieRepo
type MockMovieRepoMockRecorder struct {
	mock *MockMovieRepo
}

// NewMockMovieRepo creates a new mock instance
func NewMockMovieRepo(ctrl *gomock.Controller) *MockMovieRepo {
	mock := &MockMovieRepo{ctrl: ctrl}
	mock.recorder = &MockMovieRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMovieRepo) EXPECT() *MockMovieRepoMockRecorder {
	return m.recorder
}

// MovieDetail mocks base method
func (m *MockMovieRepo) MovieDetail(arg0 string) (*model.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MovieDetail", arg0)
	ret0, _ := ret[0].(*model.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MovieDetail indicates an expected call of MovieDetail
func (mr *MockMovieRepoMockRecorder) MovieDetail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MovieDetail", reflect.TypeOf((*MockMovieRepo)(nil).MovieDetail), arg0)
}

// SearchMovie mocks base method
func (m *MockMovieRepo) SearchMovie(arg0, arg1 string) (*model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovie", arg0, arg1)
	ret0, _ := ret[0].(*model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovie indicates an expected call of SearchMovie
func (mr *MockMovieRepoMockRecorder) SearchMovie(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovie", reflect.TypeOf((*MockMovieRepo)(nil).SearchMovie), arg0, arg1)
}
